export { LoginPage } from './LoginPage'
export { DashboardPage } from './DashboardPage'
export { ModelListPage } from './ModelListPage'
export { ModelFormPage } from './ModelFormPage'
export { ModelViewPage } from './ModelViewPage'
